version: "2"

services:
  rest-api:
    image: rest-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "rest-api"
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    env_file: .env
    ports:
      - ${APP_PORT}:8080
    volumes:
      - .:/var/www
    networks:
      - default
      - bridge-network
networks:
  default:
    driver: bridge
  bridge-network:
    external: true